version: "3.8"
services:
  strapi:
    build:
      context: strapi/
      dockerfile: Dockerfile.strapi
    ports:
      - "1337:1337"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
    volumes:
      - ./strapi/config:/app/config
      - ./strapi/src:/app/src
      - ./strapi/yarn.lock:/app/yarn.lock
      - ./strapi/.env:/app/env
      - ./strapi/uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - my-network

  next:
    build:
      context: frontend/
      dockerfile: Dockerfile.next
    ports:
      - "3000:3000"
    environment:
      API_TOKEN: ${API_TOKEN}
    depends_on:
      - strapi
    volumes:
      - ./frontend/:/app
      - ./frontend/.next:/app/.next
    restart: always
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
  nodem: {}
