version: "3.8"
services:
  strapi:
    build:
      context: strapi/
      dockerfile: Dockerfile.strapi
    restart: on-failure
    ports:
      - "1337:1337"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./strapi/config:/app/config
      - ./strapi/src:/app/src
      - ./strapi/yarn.lock:/app/yarn.lock
      - ./strapi/.env:/app/env
      - ./strapi/uploads:/app/uploads
      - ./strapi/database:/app/database
    depends_on:
      - postgres
    networks:
      - my-network

  next:
    build:
      context: frontend/
      dockerfile: Dockerfile.next
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    volumes:
      - ./frontend/:/app
      - ./frontend/.next:/app/.next
    restart: always
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
