name: Deploy to Server

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: root
          key: ${{secrets.DEPLOY_KEY}}
          script: |
            ../update.sh
